using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using SmartSolarMicrogrid.Api.Configuration;
using SmartSolarMicrogrid.Api.Data;
using SmartSolarMicrogrid.Api.Middleware;
using SmartSolarMicrogrid.Api.Services;
var builder=WebApplication.CreateBuilder(args);
builder.Services.Configure<MongoDbOptions>(builder.Configuration.GetSection("MongoDb"));
builder.Services.Configure<JwtOptions>(builder.Configuration.GetSection("Jwt"));
var jwt=builder.Configuration.GetSection("Jwt").Get<JwtOptions>()!;
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o=>o.TokenValidationParameters=new TokenValidationParameters{ValidateIssuer=true,ValidateAudience=true,ValidateLifetime=true,ValidateIssuerSigningKey=true,ValidIssuer=jwt.Issuer,ValidAudience=jwt.Audience,IssuerSigningKey=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwt.Key)),ClockSkew=TimeSpan.Zero});
builder.Services.AddAuthorization(); builder.Services.AddControllers();
builder.Services.AddCors(o=>o.AddPolicy("Clients",p=>p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));
builder.Services.AddEndpointsApiExplorer();builder.Services.AddSwaggerGen(o=>{o.SwaggerDoc("v1",new OpenApiInfo{Title="Smart Solar Microgrid API",Version="v1"});o.AddSecurityDefinition("Bearer",new OpenApiSecurityScheme{Name="Authorization",Type=SecuritySchemeType.Http,Scheme="bearer",BearerFormat="JWT",In=ParameterLocation.Header});o.AddSecurityRequirement(new OpenApiSecurityRequirement{{new OpenApiSecurityScheme{Reference=new OpenApiReference{Type=ReferenceType.SecurityScheme,Id="Bearer"}},Array.Empty<string>()}});});
builder.Services.AddSingleton<MongoContext>();builder.Services.AddScoped<IAuthService,AuthService>();builder.Services.AddScoped<IUserService,UserService>();builder.Services.AddScoped<IProsumerService,ProsumerService>();builder.Services.AddScoped<IStationService,StationService>();builder.Services.AddScoped<ISlotService,SlotService>();builder.Services.AddScoped<IReservationService,ReservationService>();builder.Services.AddSingleton<DatabaseSeeder>();
var app=builder.Build(); app.UseMiddleware<ExceptionHandlingMiddleware>();app.UseSwagger();app.UseSwaggerUI();app.UseCors("Clients");app.UseAuthentication();app.UseAuthorization();app.MapControllers();using(var scope=app.Services.CreateScope())await scope.ServiceProvider.GetRequiredService<DatabaseSeeder>().SeedAsync();app.Run();
