using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
namespace SmartSolarMicrogrid.Api.Models;
public abstract class Entity { [BsonId, BsonRepresentation(BsonType.ObjectId)] public string Id { get; set; } = ObjectId.GenerateNewId().ToString(); public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; }
public sealed class User : Entity { public string Username { get; set; } = ""; public string PasswordHash { get; set; } = ""; public string Role { get; set; } = ""; public string? ProsumerNic { get; set; } public bool IsActive { get; set; } = true; }
public sealed class Prosumer : Entity { public string Nic { get; set; } = ""; public string FullName { get; set; } = ""; public string Email { get; set; } = ""; public string Phone { get; set; } = ""; public string Address { get; set; } = ""; public bool IsActive { get; set; } = true; public bool DeactivationRequested { get; set; } }
public sealed class SolarStationInfo : Entity { public string Name { get; set; } = ""; public string Location { get; set; } = ""; public double Latitude { get; set; } public double Longitude { get; set; } public decimal CapacityKwh { get; set; } public int BatteryStorageSlots { get; set; } public bool IsActive { get; set; } = true; }
public sealed class EnergyBookingSlot : Entity { public string StationId { get; set; } = ""; public DateTime StartTime { get; set; } public DateTime EndTime { get; set; } public decimal AvailableKwh { get; set; } public decimal PricePerKwh { get; set; } public bool IsActive { get; set; } = true; }
public enum ReservationStatus { Pending, Confirmed, Cancelled, Completed }
public sealed class EnergyReservation : Entity { public string ProsumerNic { get; set; } = ""; public string StationId { get; set; } = ""; public string SlotId { get; set; } = ""; public decimal EnergyKwh { get; set; } public ReservationStatus Status { get; set; } = ReservationStatus.Pending; public string QrToken { get; set; } = Guid.NewGuid().ToString("N"); public DateTime? FinalizedAt { get; set; } public string? FinalizedBy { get; set; } }
